### ISSUE TITLE
Target directory for 'new' needs to pre-exist?

### ISSUE THREAD

**Issue by pharrisee** [nullbio/abcweb#3]
It seems that the target folder for 'abcweb new <import-path>' needs to already exist and be an initialised git repo?

A note in the docs to this effect may be helpful.

**Comment by nullbio** [comment]
Hi. No the folder does not need to exist and be an initialized repo -- the generator will actually git init your project once it has been generated, the problem you refer to is actually a bug that requires you to run abcweb from the abcweb project folder. It was fixed at one point, but seems it's made its way back in. In either case, I should let you know this project is still under development and so the master branch is all over the place, it's not safe for use yet. Having said that, it's not far off either. One or two weeks and I think an initial release will be ready. Thanks.

**Comment by nullbio** [comment]
Issue has been fixed in master now, thanks for letting me know.

**Comment by pharrisee** [comment]
Thanks for the fix, and I'll be watching this, looks interesting.  Thanks for the work.

**Comment by pharrisee** [comment]
Just FYI, pulled master, 'abcweb new' now works as expected :)

**Comment by nullbio** [comment]
Glad to hear :) Out of curiosity, how'd you land on this project? Github search?

**Comment by pharrisee** [comment]
I have a bookmark to a github search of updated Go repos , I check that about 1-2 times a day and this appeared in the list :)  It's interesting to say the least.

URL I use: 

https://github.com/search?l=go&q=stars%3A%3E1&s=updated&type=Repositories

**Comment by nullbio** [comment]
Hi @pharrisee -- Just wanted to let you know I've done the first official release and have begun semantic versioning. Thanks.
